### PR TITLE
test: Move to Jest insted of Mocha

### PR DESCRIPTION
**Pull request by wolfy1339**

### CODE REVIEW

**Comment by wolfy1339** [comment]
Tests fail due to these errors:
**TLDR**: 

- All arguments for the `merge` function need to have a value, they can never be empty
- Missing `baseUrl` property in the `parse()` tests

<details>
Full error text

```
 FAIL  test/merge.test.ts
  ● Test suite failed to run

    TypeScript diagnostics (customize using `[jest-config].globals.ts-jest.diagnostics` option):
    test/merge.test.ts:79:21 - error TS2554: Expected 1-2 arguments, but got 0.

    79     const options = endpoint.merge();
                           ~~~~~~~~~~~~~~~~

      src/types.ts:36:6
        36     (route: Route, parameters?: Parameters): Defaults;
                ~~~~~~~~~~~~
        An argument for 'route' was not provided.

 FAIL  test/parse.test.ts
  ● Test suite failed to run

    TypeScript diagnostics (customize using `[jest-config].globals.ts-jest.diagnostics` option):
    test/parse.test.ts:16:21 - error TS2345: Argument of type '{ method: string; url: string; org: string; type: string; }' is not assignable to parameter of type 'Endpoint'.
      Type '{ method: string; url: string; org: string; type: string; }' is not assignable to type '{ method: Method; }'.
        Types of property 'method' are incompatible.
          Type 'string' is not assignable to type 'Method'.

    16     expect(endpoint(input)).toEqual(
                           ~~~~~
    test/parse.test.ts:33:20 - error TS2345: Argument of type '{ method: string; url: string; headers: { accept: string; }; mediaType: { previews: string[]; }; }' is not assignable to parameter of type 'Defaults'.
      Property 'baseUrl' is missing in type '{ method: string; url: string; headers: { accept: string; }; mediaType: { previews: string[]; }; }' but required in type '{ method: Method; baseUrl: string; headers: { accept: string; "user-agent": string; }; mediaType: { format: string; previews: string[]; }; }'.

    33     endpoint.parse(input);
                          ~~~~~

      src/types.ts:136:3
        136   baseUrl: string;
              ~~~~~~~
        'baseUrl' is declared here.
```
</details>

**Comment by gr2m** [comment]
Thanks @wolfy1339 I’ll look into it

**Comment by gr2m** [comment]
The remaining one is tricky

```
$ ljest
 PASS  test/merge.test.ts
 PASS  test/parse.test.ts
 PASS  test/defaults.test.ts
 FAIL  test/endpoint.test.ts
  ● Test suite failed to run

    TypeScript diagnostics (customize using `[jest-config].globals.ts-jest.diagnostics` option):
    test/endpoint.test.ts:260:12 - error TS2532: Object is possibly 'undefined'.

    260     expect(options.request.agent).toBeInstanceOf(Agent);
                   ~~~~~~~~~~~~~~~

Test Suites: 1 failed, 3 passed, 4 total
Tests:       14 passed, 14 total
Snapshots:   0 total
Time:        6.48s
Ran all test suites.
```

Here is the whole test

```js
  it("request.agent", () => {
    const options = endpoint("GET /", {
      request: {
        agent: new Agent()
      }
    });

    expect(options.request.agent).toBeInstanceOf(Agent);
  });
```

Basically what the type definition should implement is this: what ever `request` option is passed to `endpoint(route, options) or `endpoint(options)` shall be returned as is. Do you know if that can be done with Typescript?

**Comment by wolfy1339** [comment]
Unfortunately, I don't think so.

**Comment by gr2m** [comment]
> Unfortunately, I don't think so.

I wonder how this is working

```ts
const a = {}
const b = Object.assign(a, { foo: { bar: 'baz' } })
console.log(b.foo.bar) 
```

[playground link](https://www.typescriptlang.org/play/index.html#src=const%20a%20%3D%20%7B%7D%0D%0Aconst%20b%20%3D%20Object.assign(a%2C%20%7B%20foo%3A%20%7B%20bar%3A%20'baz'%20%7D%20%7D)%0D%0Aconsole.log(b.foo.bar)%20)

I’ll do some research 🕵

**Comment by wolfy1339** [comment]
That works because you aren't specifying the return type/interface. But in our case, we need to specify them or else the computed valued from the compiler are a jumbled mess

**Pull request merged**
